class PowerUps {
  
}
  // Ideas:
  // 1, Invert Gravity (can also be sideways)
  // 2, Speed up time (framerate 60) (only for cell that gets powerup?)
  // 3, Slow down time? (framerate 15) (only for cell that gets powerup?)
  // 4, Reverse time? (unlikely)
  // 5, Invert controls? (maybe only good powerups?)
  // 6, Gain Size (probably just size += random 1-10)
  // 7, Lose Size (maybe only good powerups?)
  // 8, Instant death (maybe only good powerups?)
  // 9, Become largest enemy on map (Seems too OP)
  // 10, Become smallest enemy on map (maybe only good powerups?)
  // 11, Immunity (limited on time, maybe 5 secs?)
  // 12, Become rectangle (no use just funny) (might replace with name easter egg)
  // 13, Extra life (after 1st death, you randomly respawn with same size?)
  // 14, Extra enemy (adds an enemy to the "numEnemies" varable)
  // 15, Lose an enemy (subtracts an enemy to the "numEnemies" varable)
  // 16, Go up 1 LV? (add 100 points to size)
  // 17, Clear all enemies on screen (seems too OP)
  // 18, Go up to HARD mode (limited on time?, 5 secs?) (if already on HARD, stay and if on easy, move to Normal?)
  // 19, Go down to easy mode (limited on time?, 5 secs?) (if already on easy, stay and if on HARD, move to Normal?)
  // 20, FREEZE controls (no inputs for 1 second?)
  // 21, FREEZE self (stuck in place) (maybe only good powerups?)
  // 22, FREEZE enemies (stuck in place)
  // 23, FREEZE nearest enemy (or player)
  // 24, enemies become immune (no collision for 5?) (maybe only good powerups?)
  // 25, enemies become rectangles (lol) (maybe)
  // 26, Maybe speed up only the player (or whatever hits the powerup)? (change the framerate only for whoever got the powerup)
